name: Deployment

on:
  push: 
  workflow_dispatch:   

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      
      - name: Download packages
        run: npm ci
      
      - name: Build
        run: npm run build
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: dist
  
  deploy:
    needs: build

    permissions:
      id-token: write
      pages: write
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure Github Pages
        uses: actions/configure-pages@v4

      - name: Deploy to Github Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages